### ISSUE TITLE
Fetching gif returns wrong header

### ISSUE THREAD

**Issue by kovacs** [Giphy/GiphyAPI#140]
Hello,

I have an app that sends giphys via Twilio and the changes to the response header for fetching gifs is breaking. You guys are returning an HTML header, and response, when Twilio is making their request. I suspect that maybe Twilio isn't setting the content type in the header and if nothing is specified you guys return HTML by default? But when I curl an image I get back an image instead of HTML. e.g. curl https://media1.giphy.com/media/3o6ZtaO9BZHcOjmErm/giphy-downsized.gif

I can't be the first person to run across this problem as I know using Twilio to send giphys is pretty popular but I can't seem to find where the problem lies.. with you guys or with Twilio's requests. 

Any help you can provide to resolve this issue would be great. 

-Michael

**Comment by kovacs** [comment]
Msg	Attempt to retrieve MediaUrl returned an unsupported Content-Type.
EmailNotification	false
contentType	text/html
LogLevel	ERROR
url	https://media2.giphy.com/media/bOmXDVQAR7gaY/giphy-downsized.gif

**Comment by kovacs** [comment]
From Twilio's REST API docs - https://www.twilio.com/docs/api/rest/sending-messages

"Content types for MediaUrl validation are fetched via the content-type header at the provided URLs. If the content-type header does not match the media, Twilio will reject the request. Twilio supports image/gif, image/png, and image/jpeg mime-types and accepts many others."

This used to work just fine for years but something changed on either your side of Twilio's side. Either their client doesn't request properly or you stopped responding with the right header.

**Comment by dfinkler** [comment]
Hi @kovacs 
Your issue should be fixed once you apply the correct content accept headers to your requests.  Please take a look at our documentation for more details:

https://developers.giphy.com/docs/#rendition-guide

"When making requests that return GIF objects, the accept http header can be used to toggle the content type you will receive in return. By including accept: image/* the binary media file will be returned, otherwise some markup embedding the GIF is returned."

**Comment by kovacs** [comment]
Hi @dfinkler 

Yeah I know about the header content accept type. I'm not the one making the request, Twilio is. They said that you guys were aware of the problem and there's a fix in place. Just need to try it out and see but thanks for replying to this issue. Hopefully it'll all be fixed when I try to send a giphy URL via the Twilio API.

**Comment by andersonreinkordt** [comment]
This still appears to be an issue. I am currently attempting to pass giphy gif links as media_url to twilio to send in sms. Can this be reopened or addressed? Thanks!

**Comment by andersonreinkordt** [comment]
Nevermind me. I found my issue. :)
